import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";

import QueryClientProvider from "@/components/query-client-wrapper";
import { Toaster } from "@/components/ui/sonner";

import "./globals.css";

const publicSans = Public_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${publicSans.className} antialiased`}>
        <QueryClientProvider>
          {children}
          <Toaster />
        </QueryClientProvider>
      </body>
    </html>
  );
}
